# Uncomment the next line to define a global platform for your project
platform :ios, '9.0' # Make sure this matches your minimum requirement

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  # Uncomment these lines to add permissions
  'PERMISSION_MICROPHONE=1'
  'PERMISSION_SPEECH_RECOGNIZER=1'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
